# Build the Doxygen documentation (User manual and API reference) and publish it to www.reactphysics3d.com website
name: Publish Documentation 

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
    branches:
      - documentation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  documentation:
    name: Build/Publish Documentation
    runs-on: ubuntu-latest
    #needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake doxygen
          cmake --version
          doxygen --version

      - name: CMake Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -S . \
            -B build \
            -DRP3D_GENERATE_DOCUMENTATION=True \
            -DRP3D_COMPILE_TESTS=False \
            -DRP3D_COMPILE_TESTBED=False

      - name: Build Documentation
        shell: bash
        run: cmake --build build/ 
